#!/bin/sh
set -e
package_name=htop-hide
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/htop.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/htop.desktop"
;;
esac
exit 0
