#!/bin/sh
set -e
package_name=htop-hide
mkdir -p "/usr/share/dpkgdivert/htop-hide"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/htop-hide/usrshareapplicationshtop.desktop" --rename "/usr/share/applications/htop.desktop"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/applications/htop.desktop")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/htop-hide/usrshareapplicationshtop.desktop" --rename "/usr/share/applications/htop.desktop"
fi
;;
esac
exit 0
